first.yaml

diff --git a/.github/workflows/run-container-scan-supermario-image.yaml b/.github/workflows/run-container-scan-supermario-image.yaml
--- a/.github/workflows/run-container-scan-supermario-image.yaml
+++ b/.github/workflows/run-container-scan-supermario-image.yaml
@@ -1,38 +1,46 @@
 name: "Run Container Scan on Super Mario Docker Image with Quality Gate"
- 
+
 on:
   push:
     branches:
       - main
- 
+
 env:
   VERSION: $(( $(cat version.txt) + 1 ))
-  
+
 jobs:
-  
+
   run_container_image_scan_on_supermario_docker_image:
-    runs-on: ubuntu-latest	
- 
+    runs-on: ubuntu-latest
+
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v3
- 
+
       - name: Login to Docker Hub
         run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
-        
+
       - name: Get Docker Image from Docker Hub
         run: |
           docker pull docker.io/rahuldocker628/mariogitopsproject:${{ env.VERSION }}
           docker save -o supermariolatestdockerimage.tar docker.io/rahuldocker628/mariogitopsproject:${{ env.VERSION }}
-     
-      - name: Run Trivy vulnerability scanner in tarball mode
-        uses: aquasecurity/trivy-action@0.28.0
-        with:
-          input: /github/workspace/supermariolatestdockerimage.tar
-          exit-code: '0'
-          ignore-unfixed: true
-          vuln-type: 'os,library'
-          severity: 'CRITICAL,HIGH'
+
+      - name: Login to GitHub Container Registry
+        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
+
+      - name: Install Trivy
+        run: |
+          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b $(pwd)
+          mkdir -p ~/.cache/trivy/db
+
+      - name: Pre-Cache Trivy DB
+        run: |
+          ./trivy image --download-db-only --cache-dir ~/.cache/trivy/db || echo "Using cached database if download fails"
+
+      - name: Run Trivy vulnerability scanner in tarball mode with cached DB
+        run: |
+          ./trivy image --input supermariolatestdockerimage.tar --severity CRITICAL,HIGH --exit-code 1 --cache-dir ~/.cache/trivy/db --skip-update
+
          
  
 
